### ISSUE TITLE
layout->scalar not work for vec3

### ISSUE THREAD

**Issue by yyc-git** [maierfelix/webgpu#12]
Hello!

the example code is here:
ray-closest-hit.rchit:
```glsl
struct Vertex
{
  vec3 pos;
};

// error because of the vec3! if change Vertex.pos->vec3 to vec4(e.g. vec4 pos), it can work!!!
layout(scalar, set = 1, binding = 0) buffer Vertices { Vertex v[]; } vertices;
```

I know that std140/std430 can't work with vec3, but the scalar should support working with vec3!!! This is a bug???
Thanks very much!

**Comment by maierfelix** [comment]
Most likely related to glsl and not this project. Closing this
