### ISSUE TITLE
GPUShaderModule has new Dawn Error.

### ISSUE THREAD

**Issue by dcerisano** [maierfelix/webgpu#21]
Just  a headsup, I compile against the official Dawn build, and there are recent changes there affecting your webgpu-napi. You won't see these until you rebase your dawn-ray-tracing repo.

Error is:

```
../src/GPUShaderModule.cpp:23:14: error: no member named 'code' in 'WGPUShaderModuleDescriptor'
  descriptor.code = nullptr;
  ~~~~~~~~~~ ^
../src/GPUShaderModule.cpp:24:14: error: no member named 'codeSize' in 'WGPUShaderModuleDescriptor'
  descriptor.codeSize = 0;
  ~~~~~~~~~~ ^
2 errors generated.
```
Related to [this upstream Dawn change](https://dawn.googlesource.com/dawn/+/2eca22f6d75388f4e8acd51c553a3ff382039644).

Local Fix:

Removed code and codeSize initializers (line 23 and 24).

**Comment by maierfelix** [comment]
The next dawn upstream change will be somewhat big and I didn't start on it yet.

**Comment by maierfelix** [comment]
Fixed by https://github.com/maierfelix/webgpu/commit/c1151a1c27d707798bf70906972f557935b3203a
