### ISSUE TITLE
MacOS build is broken

### ISSUE THREAD

**Issue by maierfelix** [maierfelix/webgpu#22]
It seems that the addon file is missing. Can't fix it myself as I don't have a Mac.

**Comment by maierfelix** [comment]
Adding @pjoe

**Comment by pjoe** [comment]
what particular file is missing?

**Comment by pjoe** [comment]
looks like the dawn build is actually failing: https://github.com/maierfelix/webgpu/runs/677237598?check_suite_focus=true#step:8:352

Not sure why CI doesn't detect this failure properly

**Comment by maierfelix** [comment]
I think it's again the issue with the *lib* prefix.

**Comment by pjoe** [comment]
yeah looks like it ... will try to figure out when I have som time

**Comment by maierfelix** [comment]
I just pushed a fix, lets see

**Comment by pjoe** [comment]
🤞

**Comment by maierfelix** [comment]
looking good, should be fixed in `0.1.14`
