### ISSUE TITLE
Support bindless texture???

### ISSUE THREAD

**Issue by yyc-git** [maierfelix/webgpu#23]
Need it in ray tracing! 
Will support it? Thanks very much!

**Comment by maierfelix** [comment]
This is how I did it in my path tracer, see [here](https://github.com/maierfelix/WebGPU-Path-Tracer/blob/master/shaders/shading/ray-closest-hit.rchit#L192)

**Comment by yyc-git** [comment]
@maierfelix you have use texture array instead of bindless texture~

texture array require each texture has the same size in the array. it's more limit than bindless texture.

**Comment by maierfelix** [comment]
WebGPU doesn't support bindless textures/resources, the current alternative is descriptor indexing which is enabled in my fork. If you want to sample textures with different sizes, then use a plain buffer and do the texture filtering (e.g. linear) inside the shader

**Comment by yyc-git** [comment]
@maierfelix Thanks very much for your suggestion! I will investigate it~ Thank you!
