### ISSUE TITLE
MacOS prebuilts are missing

### ISSUE THREAD

**Issue by devknoll** [maierfelix/webgpu#6]
The 0.1.1 version includes binaries for win32 and linux, but not macOS. Can you publish a new version with those? Thanks :smile:

**Comment by maierfelix** [comment]
My laptop recently died and I lost my hackintosh by this. You could try building it yourself, since I won't have access to Mac OS for quite some time now.

**Comment by devknoll** [comment]
I’ll take a look. In the meantime, you might be interested in looking at [GitHub Actions](https://github.com/features/actions) for release automation. GitHub offers OSS projects free Windows/MacOS VMs that you could use in lieu of a Hackintosh 😄

**Comment by pjoe** [comment]
This is fixed in #18 and #20
