### ISSUE TITLE
run the ray tracing example Error:invalid stage for 'shader_stage' #pragma: 'raygen'

### ISSUE THREAD

**Issue by yyc-git** [maierfelix/webgpu#8]
Hello @maierfelix , Thanks For your project!

I have meet another error!
I can run other examples except the ray tracing example!!!

when I run the ray tracing example by:
```html
node --experimental-modules examples/ray-tracing/index.mjs
```

the windows open , then close and render nothing!

I have change the examples/ray-tracing/index.mjs for debug:
1、comment the code after:
```js
  let rayMissShaderModule = device.createShaderModule({
    code: fs.readFileSync(`${baseShaderPath}/ray-miss.rmiss`, "utf-8")
  });
```
2、run the ray tracing example by:
```html
node --experimental-modules examples/ray-tracing/index.mjs
```

It have a Error:
```html
D:\Github\webgpu-master>node --experimental-modules examples/ray-tracing/index.mjs
(node:268) ExperimentalWarning: The ESM module loader is experimental.
Info: Windows Error: 126
D:\Github\webgpu-master\index.js:35
              case "Error": throw new Error(msg); break;
                            ^

Error: shader:3: error: '#pragma': invalid stage for 'shader_stage' #pragma: 'raygen'

    at Immediate.<anonymous> (D:\Github\webgpu-master\index.js:35:35)
←[90m    at processImmediate (internal/timers.js:456:21)←[39m
```

**I can run the tiny-rtx project's example(by npm run start) successfully!**

# So How to solve the Error??? Thanks very much!!!

examples/ray-tracing/index.mjs(with my change that only comment the code):
```js
...

(async function main() {

  ...

  // ray-tracing shaders
  let rayGenShaderModule = device.createShaderModule({
    code: fs.readFileSync(`${baseShaderPath}/ray-generation.rgen`, "utf-8")
  });
  let rayCHitShaderModule = device.createShaderModule({
    code: fs.readFileSync(`${baseShaderPath}/ray-closest-hit.rchit`, "utf-8")
  });
  let rayMissShaderModule = device.createShaderModule({
    code: fs.readFileSync(`${baseShaderPath}/ray-miss.rmiss`, "utf-8")
  });

  //comment all the code after!
})();

```

**Comment by maierfelix** [comment]
I found the error, it's inside the dawn fork. Go to `dawn/third_party/glslang`, open `BUILD.gn` and do the following:

In Line 57 change:
````
  # Configure Glslang's interface to include HLSL-related entry points.
  defines = [ "ENABLE_HLSL=1" ]
````
To:
````
  # Configure Glslang's interface to include HLSL-related entry points.
  defines = [ "ENABLE_HLSL=1", "NV_EXTENSIONS=1" ]
````

In line 85 change:
````
  defines = [ "SHADERC_IMPLEMENTATION" ]
````
To:
````
  defines = [ "SHADERC_IMPLEMENTATION", "NV_EXTENSIONS=1" ]
````

Now rebuild dawn and the webgpu project, afterwards you should be able to run the RT example.

Thanks for reporting

**Comment by yyc-git** [comment]
@maierfelix   Yes!It work!!! Thanks very much!!!

by the way, your answer has tiny bug: 
need to fix dawn-ray-tracing/third_party/shaderc/BUILD.gn instead of the one of glslang.


And still has a tiny bug:
after I fix the BUILD.gn, I run "gclient sync" in dawn-ray-tracing project, it error:
```html
D:\Github\dawn-ray-tracing>gclient sync
Syncing projects:  70% (17/24) third_party\vulkan-headers

third_party\shaderc (ERROR)
----------------------------------------
[0:00:05] Started.
[0:00:05] Finished running: git config remote.origin.url
[0:00:06] Finished running: git rev-list -n 1 HEAD
[0:00:06] Finished running: git rev-parse --abbrev-ref=strict HEAD
----------------------------------------
Error: 13>
13> ____ third_party\shaderc at 1059f43a379ff9f1b5d00b8afcc2ec2435f592c4
13>     You have unstaged changes.
```

I can ignore the error because I only have to build the dawn-ray-tracing project after fix the BUILD.gn without "gclient sync"! so it's unimportant!

Thanks for your reply and your great work!!!
