### ISSUE TITLE
include glsl in ray tracing shader error

### ISSUE THREAD

**Issue by yyc-git** [maierfelix/webgpu#9]
Hello @maierfelix !
my code is:
rchit glsl:
```glsl
#version 460
#extension GL_NV_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#pragma shader_stage(closest)

#include "wavefront.glsl"

...
```
wavefront.glsl:
```glsl
struct sceneDesc
{
  int  objId;
  int  txtOffset;
  mat4 transfo;
  mat4 transfoIT;
};
```

when run the code, it error:
```html
error: '#include' : #error unexpected include directive for header name: wavefront.glsl
```

How to include glsl???
Thanks very much!!!

**Comment by maierfelix** [comment]
The included glsl compiler doesn't handle includes, it's up to the application. You have to recursively lookup the content of the included file and inline it. This is how I do it in my projects - see [here](https://gist.github.com/maierfelix/21738a65b3cea4b609e2436cb1e07da2#file-glsl-includes-inliner-mjs-L47).

Alternatively you can use the [nvk-essentials package](https://www.npmjs.com/package/nvk-essentials) which contains a GLSL compiler and support for includes.

**Comment by yyc-git** [comment]
Thanks for your reply!!!

Yes, I can use "include" by import your "loadShaderFile"(created from [your project](https://gist.github.com/maierfelix/21738a65b3cea4b609e2436cb1e07da2#file-glsl-includes-inliner-mjs-L47)).
But it has a little bug:
inliner.mjs
```js
import fs from "fs";
//should add this line!
import path from "path";

...
```


So the complete code to support include is:
index.mjs
```js
//should move inliner.mjs to my project

import { loadShaderFile } from "./inliner.mjs";
...
  // rasterization shaders
  let vertexShaderModule = device.createShaderModule({
    code: loadShaderFile(`${baseShaderPath}/screen.vert`)
  });
  let fragmentShaderModule = device.createShaderModule({
    code: loadShaderFile(`${baseShaderPath}/screen.frag`)
  });

  // ray-tracing shaders
  let rayGenShaderModule = device.createShaderModule({
    code: loadShaderFile(`${baseShaderPath}/ray-generation.rgen`)
  });
  let rayCHitShaderModule = device.createShaderModule({
    code: loadShaderFile(`${baseShaderPath}/ray-closest-hit.rchit`)
  });
  let rayMissShaderModule = device.createShaderModule({
    code: loadShaderFile(`${baseShaderPath}/ray-miss.rmiss`)
  });
```

ray-closest-hit.rchit
```glsl
#version 460
...
#extension GL_GOOGLE_include_directive : enable
#pragma shader_stage(closest)

#include "wavefront.glsl"
```


wavefront.glsl
```glsl
//define the export code like:
struct Data1
{
  float objId;
};

int getData2(){
  return 1;
}
```
